### ISSUE TITLE
screenshot of app 

### ISSUE THREAD

**Issue by DEMETRIUSCARTER** [wickedslug883/Hackstreet-Boys#12]
<img width="842" alt="Screen Shot 2022-09-18 at 9 37 38 PM" src="https://user-images.githubusercontent.com/108381693/190941628-8a14c31d-0ea8-43c3-96a2-7c3cf366ead6.png">

**Comment by wickedslug883** [comment]
Nice work! Issue closed! WOOOOOOOOO
